[workspace]

members=["tutor-nodb", "tutor-db"]


[package]
name = "ezytutors"
version = "0.1.0"
authors = ["elvq <eric.levanquyen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
